# Generated by Django 2.1 on 2019-01-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20190107_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usrID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
